#!/bin/bash

export ARCH="arm64"
export KBUILD_BUILD_USER="wulan17"
export KBUILD_BUILD_HOST="Github"
export KERNEL_NAME="Mayuri"
export SHIP_DTBO=0 # Set to 1 to ship dtbo.img, 0 to not ship

## Notes:
# this script running in aarch64 workflows
# so only use clang for aarch64
export CLANG_URL="https://github.com/MayuriLabs/tc/releases/download/22.0.0git-29639420459/Mayuri-clang_22.0.0git-bookworm-aarch64-de03d4304.tar.xz"

export CORES=$(nproc --all)

# START OF DO NOT EDIT
export BASE_DIR="$(pwd)"
export ZIP_DIR="$BASE_DIR"/AnyKernel
export CLANG_NAME="$(basename "$CLANG_URL")"
export PATH="$BASE_DIR/clang/bin:/usr/lib/ccache:$PATH"

# autogenerated by do_write_config
# Reserved
# END OF DO NOT EDIT

export ZIP_NAME="$GITHUB_RUN_ID-$KERNEL_NAME-kernel-$DEVICE-resukisu-susfs-"$(env TZ='Asia/Jakarta' date +%Y%m%d)
