#!/bin/bash

export ARCH="arm64"
export KBUILD_BUILD_USER="wulan17"
export KBUILD_BUILD_HOST="Github"
export KERNEL_NAME="Mayuri"
export SHIP_DTBO=0 # Set to 1 to ship dtbo.img, 0 to not ship

## Notes:
# this script running in aarch64 workflows
# so only use clang for aarch64
export CLANG_URL="https://github.com/MayuriLabs/tc/releases/download/23.0.0git-37041309404/Mayuri-clang_23.0.0git-trixie-aarch64-52d25c7f6.tar.xz"

export CORES=$(nproc --all)

# START OF DO NOT EDIT
export BASE_DIR="$(pwd)"
export ZIP_DIR="$BASE_DIR"/AnyKernel
export CLANG_NAME="$(basename "$CLANG_URL")"
export PATH="$BASE_DIR/clang/bin:/usr/lib/ccache:$PATH"

# autogenerated by do_write_config
# Reserved
# END OF DO NOT EDIT

